# This rule is not used by the project crl-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over crl-operator.scality.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crl-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedcrl-admin-role
rules:
- apiGroups:
  - crl-operator.scality.com
  resources:
  - managedcrls
  verbs:
  - '*'
- apiGroups:
  - crl-operator.scality.com
  resources:
  - managedcrls/status
  verbs:
  - get
