apiVersion: crl-operator.scality.com/v1alpha1
kind: ManagedCRL
metadata:
  labels:
    app.kubernetes.io/name: crl-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedcrl-sample
spec:
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
  expose:
    enabled: true
    ingress:
      host: crl.example.com
