name: "Build"

on:
  workflow_call:
    inputs:
      is-development:
        description: "Whether the build is for development purposes or not"
        required: false
        default: true
        type: boolean
      is-latest:
        description: "Whether the build is for the latest tag or not"
        required: false
        default: false
        type: boolean
      is-stable:
        description: "Whether the build is for a stable release or not"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # NOTE: We fetch depth so that we can put the right `GIT` reference
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tags
        id: tags
        # If `is-development` then suffix tag with `-dev`
        # If `is-latest` then add `latest` tag
        # If not `is-stable` then suffix `-dev` to `latest
        run: |
          version="$(git describe --tags --always --dirty --match='v[0-9]*')${{ inputs.is-development && '-dev' || '' }}"
          tags="ghcr.io/${{ github.repository }}:${version}"
          if [ "${{ inputs.is-latest }}" = "true" ]; then
            tags="$tags,ghcr.io/${{ github.repository }}:latest${{ ! inputs.is-stable && '-dev' || '' }}"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args:
            VERSION=${{ steps.tags.outputs.version }}
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha,scope=crl-operator
          cache-to: type=gha,mode=max,scope=crl-operator
